name: OnEsphomeRelease
on:
  workflow_dispatch:
    inputs:
      esphome_version:
        description: 'Version of esphome released'
        required: true
        type: string

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.43.1

      - name: Update helm values
        run: |
          ESPHOME_VERSION=${{ github.event.inputs.unpoller_version }}
          yq -i ".appVersion=\"${ESPHOME_VERSION}\"" charts/esphome/Chart.yaml
          yq -i ".version=\"${ESPHOME_VERSION}\"" charts/esphome/Chart.yaml
          make helm-docs
          
          cp charts/esphome/README.md README.MD
          git add charts
          git add README.MD         
          git commit -m "chore(esphome): Updated chart and app version to ${ESPHOME_VERSION}"
          git push
